modLoader="javafml"
loaderVersion="[28,)"
credits="LepkoQQ"
authors="LepkoQQ"
[[mods]]
    modId="recycler"
    version="${file.jarVersion}"
    displayName="Recycler"
    description="Recycle your damaged tools or armor."
